apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: helm-grafana-instance
  namespace: monitoring
spec:
  deployment:
    # Do not create a new Grafana deployment; point to the existing one
    skipCreateAdminAccount: true
    baseImage: grafana/grafana:9.0.5  # Match the version of the existing Grafana instance
    ingress:
      enabled: true
  config:
    # Optional: Add Grafana config blocks if needed
    log:
      mode: "console"
      level: "info"
  instanceSelector:
    matchLabels:
      app: kube-prometheus-stack-grafana  # Match the existing Grafana deployment labels
