apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
  namespace: monitoring
spec:
  ingress:
    enabled: true
    hostname: grafana.example.com
  config:
    log:
      mode: "console"
      level: "info"
  dashboardLabelSelector:
    - matchExpressions:
        - key: "app"
          operator: In
          values:
            - grafana-dashboard
